myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment', views.leave_comment, name='leave_comment'),
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('title', max_length=200)
    article_text = models.TextField('content')
    pub_date = models.DateTimeField('publication date')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('comment author', max_length=50)
    comment_text = models.CharField('comment text', max_length=200)

    def __str__(self):
        return self.author_name

myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Articles not found!')

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a,
                                                    'latest_comments': latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Articles not found!')

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect( reverse('articles:detail', args=(a.id,)) )

myfirst/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block content %}

<h2>{{ article.article_title }}</h2>

<p>{{ article.article_text }}</p>

<em>{{ article.pub_date }}</em>

{% if article.was_published_recently %}
      <span style="color: red">New article</span>
{% endif %}

<hr>

    {% if latest_comments %}
        {% for c in latest_comments %}
            <div>
                <strong>{{ c.author_name }}</strong>
                <p>{{ c.comment_text }}</p>
            </div>
        {% endfor %}
    {% else %}
        Comments not found!
    {% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" placeholder="Your name" name="name"><br>
    <textarea name="text" placeholder="Leave your comment" cols="50" role="5"></textarea><br>
    <button type="submit">Add comment</button>

</form>

{% endblock %}

myfirst/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Last articles{% endblock %}

{% block content %}

    {% if latest_articles %}
        {% for a in  latest_articles %}
            <a href="{% url 'articles:detail' a.id %}">{{ a.article_title }}</a>
        {% endfor %}
    {% else %}
        Articles not found!
    {% endif %}

{% endblock %}

myfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My site{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>